export const SERVER_ADD_MESSAGE = 'SERVER_ADD_MESSAGE';
export const SERVER_CONNECT = 'SERVER_CONNECT';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const UPDATE_CONNECTION_STATUS = 'UPDATE_CONNECTION_STATUS';
export const CLEAR_SYSTEM_MESSAGES = 'CLEAR_SYSTEM_MESSAGES';
export const USER_DISCONNECTED_QUIT = 'USER_DISCONNECTED_QUIT';
export const USER_DISCONNECTED_TIMEOUT = 'USER_DISCONNECTED_TIMEOUT';
