// export const SERVER_ADD_MESSAGE = 'SERVER_ADD_MESSAGE';
// export const SERVER_CONNECT = 'SERVER_CONNECT';
// export const SERVER_DISCONNECT = 'SERVER_DISCONNECT';
// export const USER_DISCONNECTED = 'USER_DISCONNECTED';
// export const ADD_MESSAGE = 'ADD_MESSAGE';
// export const UPDATE_CONNECTION_STATUS = 'UPDATE_CONNECTION_STATUS';
// export const CLEAR_SYSTEM_MESSAGES = 'CLEAR_SYSTEM_MESSAGES';
// export const USER_DISCONNECTED_QUIT = 'USER_DISCONNECTED_QUIT';
// export const USER_DISCONNECTED_TIMEOUT = 'USER_DISCONNECTED_TIMEOUT';
// export const USER_FORCE_DISCONNECTED = 'USER_FORCE_DISCONNECTED';

export const SERVER_ADD_MESSAGE = 'SERVER_ADD_MESSAGE';
export const SERVER_CONNECT = 'SERVER_CONNECT';
export const SERVER_DISCONNECT = 'SERVER_DISCONNECT';
export const SERVER_RECONNECT = 'SERVER_RECONNECT';

export const CONNECT_USER = 'CONNECT_USER';
export const DISCONNECT_USER = 'DISCONNECT_USER';
export const RECONNECT_USER = 'RECONNECT_USER';
export const UPDATE_USER_ID = 'UPDATE_USER_ID';
export const ADMIN_MESSAGE = 'ADMIN_MESSAGE';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const ERROR_MESSAGE = 'ERROR_MESSAGE';
