export const SERVER_ADD_MESSAGE = 'SERVER_ADD_MESSAGE';
export const SERVER_CONNECT = 'SERVER_CONNECT';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const UPDATE_CONNECTION_STATUS = 'UPDATE_CONNECTION_STATUS';
