export const SERVER_ADD_MESSAGE = 'SERVER_ADD_MESSAGE';
export const SERVER_CONNECT = 'SERVER_CONNECT';
export const SERVER_DISCONNECT = 'SERVER_DISCONNECT';
export const SERVER_RECONNECT = 'SERVER_RECONNECT';

export const CONNECT_USER = 'CONNECT_USER';
export const DISCONNECT_USER = 'DISCONNECT_USER';
export const RECONNECT_USER = 'RECONNECT_USER';
export const UPDATE_USER_ID = 'UPDATE_USER_ID';
export const ADMIN_MESSAGE = 'ADMIN_MESSAGE';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const ERROR_MESSAGE = 'ERROR_MESSAGE';
